### ISSUE TITLE
KG incompleteness experiments

### ISSUE THREAD

**Issue by imhgchoi** [cmavro/ReaRev_KGQA#2]
Hi, I hope you are doing well.

I was curious if the `--fact_dropout` is the argument you used to retrieve the Low-Data Regime results in your paper.

Do I simply do `--fact_dropout 0.9 ` to experiment on the 10% data regime?

This experiment setting randomly drops a certain portion of the facts every iteration. Am I correct?

Thank you very much in advance :)

**Comment by imhgchoi** [comment]
Nevermind, I found the incomplete KG dataset link you posted.
Thank you!

**Comment by 2213500360** [comment]
> Nevermind, I found the incomplete KG dataset link you posted. Thank you!

Where did you find the dataset? Could you please tell me, thank you!
