### ISSUE TITLE
How to find the 'data/incomplete/' folder

### ISSUE THREAD

**Issue by toppinghand** [cmavro/ReaRev_KGQA#3]
Hello, I would like to know where should I download the incomplete dataset? looking forward to your reply.

**Comment by toppinghand** [comment]
I find it in http://curtis.ml.cmu.edu/datasets/graftnet/model_webqsp.zip

**Comment by toppinghand** [comment]
hello, i got a AttributeError: 'LSTMInstruction' object has no attribute 'question_emb' error, what is the command to train metaqa?

**Comment by cmavro** [comment]
Hi,

To run LSTM encoder, you will need to set `--relation_word_emb False` (I have slightly updated `parsing.py`). For example, you can run
```
python main.py ReaRev --entity_dim 50 --num_epoch 10 --batch_size 8 --eval_every 2  \
--data_folder data/metaqa-3hop/  --lm lstm --num_iter 2 --num_ins 3 --num_gnn 3  \
--experiment_name metaqa3 --name metaqa --relation_word_emb False
```

**Comment by toppinghand** [comment]
thank you very much!
