### ISSUE TITLE
MetaQA experiment protocol

### ISSUE THREAD

**Issue by imhgchoi** [cmavro/ReaRev_KGQA#4]
Hi, it's me again. 
I got curious about the MetaQA-3 experiment protocol you used in the paper. 
Is the MetaQA dataset uploaded in your drive the full dataset or the low-regime experiment dataset?
If it's the full dataset, then how can I reduce the portion of Train QAs, as done in your paper?
Many thanks! :)

**Comment by cmavro** [comment]
Hi!

The uploaded MetaQA  is the full dataset, but you can reduce the number of Train QAs with the `max_train` argument, e.g., `--max_train 1000`. As you can see [here](https://github.com/cmavro/ReaRev_KGQA/blob/976f1ac38e147c38ba394790d3516f04d083bbb4/dataset_load.py#L51), I simply select the first occurring Qs for training.

**Comment by imhgchoi** [comment]
I see, thank you :)
