### ISSUE TITLE
KG incompleteness experiments for MateQA-3

### ISSUE THREAD

**Issue by 2213500360** [cmavro/ReaRev_KGQA#6]
In your paper, you obtained good results on the incomplete datasets of Webqsp and MateQA-3. Can you provide the incomplete data you used in your experiment on MateQA-3? THX

**Comment by cmavro** [comment]
Hi,

We drop 50% of the edges during dataloading. 
We do not have a preprocessed dataset for this. 

Best,
Costas

**Comment by 2213500360** [comment]
thank you for your reply.

**Comment by 2213500360** [comment]
I'm sorry to disturb you again. I want to reproduce the results of NSM and your method on the incomplete MateQA-3 dataset in your paper. However, I found that setting the parameter fact_drop to randomly select facts may lead to different facts being sampled by the two methods. I found that even if the same random seed is set, the facts sampled by the two methods seem to be different. Sampling different facts may affect the comparison, and I would like to know how you solved this issue. THX

**Comment by cmavro** [comment]
Hi,

As an alternative, you can select specific edges to drop. This [section](https://github.com/cmavro/ReaRev_KGQA/blob/7d2a7786870c6b7a20d7c295bff7b8790cf41c03/dataset_load.py#L256)  loads each edge one-by-one, so you could potentially set:
```
for i, tpl in enumerate(sample['subgraph']['tuples']):
    if i % 2 == 0: continue
```
and skip the first edge that appears in every two edges.

**Comment by 2213500360** [comment]
I see. Thank you for your reply.

**Comment by firwww** [comment]
How to set up a 50KG metaqa? is for i, tpl in enumerate(sample['subgraph']['tuples']):
if i % 2 == 0: continue
or
--fact_drop=0.5?
or both？please！
