### ISSUE TITLE
KG incompleteness experiments for Webqsp

### ISSUE THREAD

**Issue by Dinaelin-Yip** [cmavro/ReaRev_KGQA#7]
Your work is very interesting. 
I want to conduct experiments for Webqsp 50% KG completeness. However, when I change the parameter 'fact_drop' in parsing.py to 0.5, the result is 71.14 for H1 and 58.62 for F1. Can you tell me what is the correct solution? Thanks a lot!

**Comment by cmavro** [comment]
Hi,

Thank you for your interest in our work. Could you try this solution https://github.com/cmavro/ReaRev_KGQA/issues/6#issuecomment-1520463167 ?

**Comment by Dinaelin-Yip** [comment]
Thank you for your kind reply. Do you mean that I should try the solution you have mentioned with the parameter 'fact_drop' be 1?

**Comment by Dinaelin-Yip** [comment]
Sorry, be 0, I meant.

**Comment by cmavro** [comment]
Yes, that is right, do not alter `fact_drop`.

**Comment by Dinaelin-Yip** [comment]
Thanks for your solution! However, after running the code on Webqsp with your solution, the average of F1/H1 is 66.41/53.41, much higher than the result in your paper with 50% KG completeness, which is 53.4/39.9.

**Comment by cmavro** [comment]
My misunderstanding; For **Webqsp-incomplete** (10%, 30%, 50%), we use the incomplete KGs provided by [GraftNet](https://github.com/haitian-sun/GraftNet).
